---
title: "Bump chart replica"
---

# Import libraries
```{r}
# remotes::install_github("hrbrmstr/ggchicklet")

library(tidyverse)
library(ggplot2)
library(ggtext)
library(grid)
library(treemapify)
library(patchwork)
library(ggchicklet)
library(usefunc)
library(showtext)
```

# Import data
```{r}
df <- read_csv("https://github.com/carolinacornejocastellano/bump-chart/raw/main/data.csv")
#View(df)
```

# Pivot longer, add ranks and order chronologically
```{r}
df <- df %>%
  pivot_longer(-generation, 
               names_to = "variables", 
               values_to = "dollars") %>%
  group_by(generation) %>%
  arrange(generation, 
          desc(dollars)) %>%
  mutate(ranking = row_number())

df$generation[df$generation == "silent"] <- "Silent"
df$generation[df$generation == "boomers"] <- "Boomers"
df$generation[df$generation == "gen_X"] <- "Generation X"
df$generation[df$generation == "millennials"] <- "Millennials"
df$generation[df$generation == "gen_Z"] <- "Generation Z"

df$variables[df$variables == "alcohol"] <- "Alcoholic beverages"
df$variables[df$variables == "apparel"] <- "Apparel and services"
df$variables[df$variables == "cash_contributions"] <- "Cash contributions"
df$variables[df$variables == "education"] <- "Education"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "food"] <- "Food"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "healthcare"] <- "Healthcare"
df$variables[df$variables == "housing"] <- "Housing"
df$variables[df$variables == "insurance"] <- "Personal insurance and pensions"
df$variables[df$variables == "miscellaneous"] <- "Miscellaneous expenditures"
df$variables[df$variables == "personal_care"] <- "Personal care products \n and services"
df$variables[df$variables == "reading"] <- "Reading"
df$variables[df$variables == "smoking"] <- "Tobacco products and smoking \n supplies"
df$variables[df$variables == "transportation"] <- "Transportation"


# Categorize observations with a ranking <= 9 as "Others"
df$variables[df$ranking >= 8] <- "Others"

#Aggregation in order to have all "Others" in the same row

df <- df %>%
  group_by(generation, variables) %>%
  summarise(dollars = sum(dollars))

df$ranking <- NULL

```

```{r}
x_names_ordered <- c("Silent", 
                     "Boomers", 
                     "Generation X", 
                     "Millennials", 
                     "Generation Z")
```

```{r}
x_names_full = c(
  "<span style='font-size: 9.55pt'>**Silent**</span><br>1945 or earlier<br>**$44,683**",

  "<span style='font-size: 9.55pt'>**Boomers**</span><br>1946 to 1964<br>**$62,203**",

  "<span style='font-size: 9.55pt'>**Generation X**</span><br>1965 to 1980<br>**$83,357**",

  "<span style='font-size: 9.55pt'>**Millennials**</span><br>1981 to 1996<br>**$69,061**",

  "<span style='font-size: 9.55pt'>**Generation Z**</span><br>1997 or later<br>**$41,636**"
)
```

```{r}
x_lab <- c("<span style='font-size: 10pt'>**Generation**</span><br>Birth Year Range<br>**Average Annual Expenditure**")
```


# Build custom theme

```{r}
# theme colours
color_background <- "#e5d9cf"
color_text <- "#333333"
```


```{r}

theme_bump <- function() {
  # Colors
  color_background <- "#e5d9cf"
  color_text <- "#333333"

  # Begin construction of chart
  theme_bw(base_size = 15) +

    # Format background colors
    theme(panel.background = element_rect(fill = color_background, color = color_background)) +
    theme(plot.background = element_rect(fill = color_background, color = color_background)) +
    theme(panel.border = element_rect(color = color_background)) +
    theme(strip.background = element_rect(fill = color_background, color = color_background)) +

    # Format the grid
    theme(axis.ticks = element_blank()) +
    theme(panel.grid = element_line(colour = color_background)) +

    # Format the legend
    theme(legend.position = "none") +

    # Format de caption
    theme(plot.caption = element_text(hjust = 0.6, vjust= 0.1, size = 5.45)) +

    # Format title and axis labels
    theme(plot.title = element_text(color = color_text, size = 17.5, face = "bold", hjust = 0.5, margin=margin(0,0,10,0))) +
    theme(plot.subtitle = element_text(color = color_text, size = 11, hjust = 0.5, face = "bold", margin=margin(0,0,22,0))) +
    theme(axis.title.x = element_blank()) +
    theme(axis.title.y = element_blank()) +
    theme(axis.text = element_markdown()) +
    theme(axis.text.x = element_markdown()) +
    theme(axis.text.x.top = element_markdown(color = "#3b3b3a", family = "Arial Narrow", size=7.5)) +
    theme(axis.text.y = element_blank()) +
    # theme(strip.text = element_text(face = "bold")) +
    theme(plot.tag = element_markdown(family = "Arial Narrow", lineheight = 0.1, size = 8)) +
    theme(plot.tag.position = c(0.10, 0.85)) +

    # Plot margins
    theme(plot.margin = unit(c(0.5, 0.4, 0.5, 0.65), "cm")) # top, right, bottom, left
}
```

```{r}
# Add a comma in the appropriate place in each value of four or more digits in the dollar column

df$dollars2 <- format(df$dollars, big.mark=",", trim=TRUE)

# Paste the dollar sign at the beginning of each value in the "dollar" column
df$dollars2 <- paste0("$",df$dollars2)

```


# Individual treemaps

## z

```{r}
z <- ggplot(df %>% filter(generation=="Generation Z"),
            aes(area = dollars,
                fill = variables,
                label = paste(variables, dollars2, sep = "\n")
                )) +
    geom_treemap(
                layout = "srow",
                 radius = unit(0, "pt")) +
    geom_treemap_text(
                layout = "srow",
                colour = "#fbf2dd",
                size = 7,
                fontface = "bold",
                family = "Consolas",
                min.size = 3,
                reflow = TRUE,
                padding.x = unit(2, "mm"),
                padding.y = unit(2, "mm")) +
    theme_bump() +
    #theme(aspect.ratio=1) +
    theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm")) + # top, right, bottom, left
    scale_fill_manual(values=c("#c49350",
                              "#c49350",
                              "#c49350",
                              "#c49350",
                              "#805b28",
                              "#e3b77b",
                              "#c49350",
                              "#c49350"))

z
```

## silent

```{r}
silent <- ggplot(df %>% filter(generation=="Silent"),
            aes(area = dollars,
                fill = variables,
                label = paste(variables, dollars2, sep = "\n")
                )) +
    geom_treemap(
                layout = "srow",
                 radius = unit(0, "pt")) +
    geom_treemap_text(
                layout = "srow",
                colour = "#fbf2dd",
                size = 7,
                fontface = "bold",
                family = "Consolas",
                min.size = 3,
                reflow = TRUE,
                padding.x = unit(2, "mm"),
                padding.y = unit(2, "mm")) +
    theme_bump() +
    #theme(aspect.ratio=1) +
    theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm")) + # top, right, bottom, left
    scale_fill_manual(values=c("#9a7447",
                              "#9a7447",
                              "#9a7447",
                              "#9a7447",
                              "#63431d",
                              "#ba9a73",
                              "#9a7447",
                              "#9a7447"))

silent
```

## boomers

```{r}
boomers <- ggplot(df %>% filter(generation=="Boomers"),
            aes(area = dollars,
                fill = variables,
                label = paste(variables, dollars2, sep = "\n")
                )) +
    geom_treemap(
                layout = "srow",
                 radius = unit(0, "pt")) +
    geom_treemap_text(
                layout = "srow",
                colour = "#fbf2dd",
                size = 7,
                fontface = "bold",
                family = "Consolas",
                min.size = 3,
                reflow = TRUE,
                padding.x = unit(2, "mm"),
                padding.y = unit(2, "mm")) +
    theme_bump() +
    #theme(aspect.ratio=1) +
    theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm")) + # top, right, bottom, left
    scale_fill_manual(values=c("#897d65",
                              "#897d65",
                              "#897d65",
                              "#897d65",
                              "#61563f",
                              "#baac91",
                              "#897d65",
                              "#897d65"))

boomers

```

## millennials

```{r}
millennials <- ggplot(df %>% filter(generation=="Millennials"),
            aes(area = dollars,
                fill = variables,
                label = paste(variables, dollars2, sep = "\n")
                )) +
    geom_treemap(
                layout = "srow",
                 radius = unit(0, "pt")) +
    geom_treemap_text(
                layout = "srow",
                colour = "#fbf2dd",
                size = 7,
                fontface = "bold",
                family = "Consolas",
                min.size = 3,
                reflow = TRUE,
                padding.x = unit(2, "mm"),
                padding.y = unit(2, "mm")) +
    theme_bump() +
    #theme(aspect.ratio=1) +
    theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.), "cm")) + # top, right, bottom, left
    scale_fill_manual(values=c("#6e6d6d",
                              "#6e6d6d",
                              "#6e6d6d",
                              "#6e6d6d",
                              "#4d4c4c",
                              "#9e9e9e",
                              "#6e6d6d",
                              "#6e6d6d"))
millennials
```

## x
```{r}
x <- ggplot(df %>% filter(generation=="Generation X"),
            aes(area = dollars,
                fill = variables,
                label = paste(variables, dollars2, sep = "\n")
                )) +
    geom_treemap(
                layout = "srow",
                 radius = unit(0, "pt")) +
    geom_treemap_text(
                layout = "srow",
                colour = "#fbf2dd",
                size = 7,
                fontface = "bold",
                family = "Consolas",
                min.size = 3,
                reflow = TRUE,
                padding.x = unit(2, "mm"),
                padding.y = unit(2, "mm")) +
    theme_bump() +
    #theme(aspect.ratio=1) +
    theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm")) + # top, right, bottom, left
    scale_fill_manual(values=c("#5e5d45",
                              "#5e5d45",
                              "#5e5d45",
                              "#5e5d45",
                              "#3b3a26",
                              "#96957e",
                              "#5e5d45",
                              "#5e5d45"))
x
```

# Header
```{r}
header <- ggplot() +
  annotate("text",
           x = 0.1,
           y = 0.1,
           size = 2,
           label = "This is my first line of text!\nAnother line of text.\n(Created by ggplot2)") + 
theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")) # top, right, bottom, left
header
```

```{r}
title <- data.frame(
  x = 1, y = 1, 
  label = paste(
  "<span style='color: #3d2309; font-size: 30pt'>What do Americans spend the most money on?</span>",
  "<span style='color: black; font-size: 10pt'></span>", 
  sep = "<br>"))

subtitle <- data.frame(
  x = 1, 
  y = 1, 
  label = paste(
  "<span style='color: #3d2309; font-size: 30pt'>What do Americans spend the most money on?</span>",
  "<span style='color: black; font-size: 10pt'></span>", 
  sep = "<br>"))

head <- ggplot(text) +
  geom_textbox(aes(x = x, 
                   y = y, 
                   label = label), 
               family = "Consolas",
               box.colour = "white",
               alpha=1,
               height = unit(7, "cm"),
               width = unit(15, "cm")) +
  theme_bump()

head
```

```{#r}
library(ggplot2)
library(ggtext)

df <- data.frame(
  x = 1, 
  y = 1, 
  label = paste(
          "<span style='color: red; font-size: 100pt'>1 in 6</span>",
           "<span style='color: black; font-size: 20pt'>people admitted to cheating on their partner</span>", 
          sep = "<br>"))

ggplot(df) +
  ggtext::geom_textbox(aes(x = x, y = y, label = label), box.colour = NA, width = unit(10, "cm")) +
  theme_void()
```


# Footer
```{#r}
foot <- 
```


# Patchwork

```{r}
plt <- (x / millennials) | (boomers / silent) + z
plt
```

```{r}
plt <-  ((x / millennials) | (boomers / silent) + z) +  plot_layout(heights = c(1, 6)) +
  plot_annotation(
    title = "What do Americans spend the most money on?",
    subtitle = "Este es el sutítulo",
    caption = "Data: U.S. Bureau of Labor Statistics",
    theme = theme_bump())
plt
```

# Final graph
```{r}

```


# Save plot

```{r}
ggsave("bump-alternative.png", 
       plot = last_plot(), 
       path = "C:/Users/Carolina/0_ccast/master/04_dataviz/bump-chart/bump-chart", 
       width = 8.29, 
       height = 6.88, 
       units = "in", 
       dpi = 300)
```



<!-- # Treemap -->

<!-- ```{r} -->

<!-- treemap <- df %>% ggplot( -->
<!--             aes(area = dollars, -->
<!--                 fill = variables, -->
<!--                 subgroup = generation, -->
<!--                 label = paste(variables, dollars2, sep = "\n"), -->
<!--                 )) + -->
<!--     geom_treemap( -->
<!--                 layout = "srow", -->
<!--                  radius = unit(0, "pt")) + -->
<!--   geom_treemap_text( -->
<!--                 layout = "srow", -->
<!--                 colour = "#fbf2dd", -->
<!--                 size = 9, -->
<!--                 fontface = "bold", -->
<!--                 family = "Consolas", -->
<!--                 min.size = 3, -->
<!--                 reflow = TRUE, -->
<!--                 padding.x = unit(2, "mm"), -->
<!--                 padding.y = unit(2, "mm")) + -->
<!--   geom_treemap_subgroup_border( -->
<!--     layout = "srow" -->
<!--   )+ -->
<!--   theme_alt() + -->
<!--   theme(aspect.ratio=1) + -->
<!--   scale_fill_manual(values=c("#c49350",  -->
<!--                               "#c49350",  -->
<!--                               "#c49350", -->
<!--                               "#c49350", -->
<!--                               "#c49350", -->
<!--                               "#c49350", -->
<!--                               "#805b28",  -->
<!--                               "#e3b77b", -->
<!--                               "#c49350", -->
<!--                               "#c49350")) -->
<!-- treemap -->
<!-- ``` -->

<!-- # Bar chart -->

<!-- ```{r} -->
<!-- # summarize the data so that it adds up all the spending for each of the generations -->
<!-- df_summ <- df %>% -->
<!--   group_by(generation) %>% -->
<!--   summarise(total_per_generation = sum(dollars)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Set custom colors -->
<!-- hist_colors <- c("#9c3c33", -->
<!--                 "#75140b", -->
<!--                 "#952419", -->
<!--                 "#c43324", -->
<!--                 "#752c26" -->
<!--                 ) -->

<!-- # Bar plot -->
<!-- hist <- ggplot(data = df_summ, -->
<!--   aes( -->
<!--     x = generation, -->
<!--     y = total_per_generation))+ -->
<!--   scale_x_discrete( -->
<!--        limits = x_names_ordered) + -->
<!--   geom_col(fill = hist_colors) + -->
<!--   geom_text(label = c("Silent", "Boomers", "Generation \n X", "Millennials", "Generation \n Z"), -->
<!--             colour = "#fbf2dd", -->
<!--             size = 2.5, -->
<!--             fontface = "bold", -->
<!--             family = "Consolas", -->
<!--             vjust=2) + -->
<!--   theme_alt() + -->
<!--   theme(axis.text.x = element_blank())  -->

<!-- hist -->

<!-- ``` -->

<!-- # Patchwork -->

<!-- ```{r} -->
<!-- plt <- hist / treemap -->
<!-- plt -->
<!-- ``` -->

