---
title: "code2"
output: html_document
date: "2022-12-07"
---

# Libraries
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
#library(ggimage)
```

# DF
```{r}
data <- read_csv("https://github.com/carolinacornejocastellano/bump-chart/raw/main/data2.csv")
#View(data)
```

# reorder years
```{r}
#data <- data %>% select(variables,rev(everything()))
```

# reshape
```{r}
datalong <- data %>% gather(generation,Rank,-variables)
```

# custom theme by Dominik Koch
```{r}
my_theme <- function() {
  # Colors
  color_background <- "#e5d9cf"
  color_text <- "black"

  # Begin construction of chart
  theme_bw(base_size = 15) +

    # Format background colors
    theme(panel.background = element_rect(fill = color_background, color = color_background)) +
    theme(plot.background = element_rect(fill = color_background, color = color_background)) +
    theme(panel.border = element_rect(color = color_background)) +
    theme(strip.background = element_rect(fill = color_background, color = color_background)) +

    # Format the grid
    theme(panel.grid.major.y = element_blank()) +
    theme(panel.grid.minor.y = element_blank()) +
    theme(axis.ticks = element_blank()) +

    # Format the legend
    theme(legend.position = "none") +

    # Format title and axis labels
    theme(plot.title = element_text(color = color_text, size = 20, face = "bold", hjust = 0.5, )) +
    theme(plot.subtitle = element_text(color = color_text, size = 15, hjust = 0.5, )) +
    theme(axis.title.x = element_blank()) +
    theme(axis.title.y = element_blank()) +
    theme(axis.text.x = element_text(size = 13, vjust = 0.5, hjust = 0.5, color = color_text, face = "bold")) +
    theme(axis.text.y =  element_text(size = 10, color = color_text)) +
    theme(strip.text = element_text(face = "bold")) +

    # Plot margins
    theme(plot.margin = unit(c(0.35, 0.2, 0.3, 0.35), "cm"))
}
```

# bump
```{r}
ggplot(data = datalong, aes(x = generation, y = Rank, group = variables)) +
  geom_line(aes(color = variables, alpha = 1), size = 2) +
  geom_point(aes(color = variables, alpha = 1), size = 4) +
  scale_x_discrete(limits = x_names_ordered, position = "top", expand = c(0.30, 0))+
  scale_y_reverse(breaks = 1:nrow(datalong))+
  #theme(legend.position = "none") +
  labs(x = "generation",
       y = "Rank",
       title = "American Kennel Club \nmost popular breeds") +
  theme_bump()  
  #geom_image(data=data,aes(y=1:10,x=6,image=drawing))+
  # + geom_text(data =data,aes(y=Silent,x=0.6,label=variables),hjust="right")
```

#mio
```{#r}
ggplot(data = datalong, aes(x = generation, y = Rank, group = variables)
) +
  geom_line(aes(color = variables, alpha = 1), linewidth = 6) +
  geom_point(aes(color = variables, alpha = 1), size = 10) +
  scale_y_reverse(breaks = 1:nrow(df)) +
  scale_x_discrete(limits = x_names_ordered, position = "top") +
  labs(
    x = "generation",
    y = "Rank",
    title = "HOW AMERICANS SPEND THEIR MONEY",
    subtitle = "By Age Group | 2021",
    caption = "Original author: Preethi Lodha",
  ) +
  my_theme() +
  geom_text(data =data,aes(y=Silent,x=0.6, label=variables),hjust="center") + #FIXME
  scale_color_manual(values = c(
    "#9c6255",
    "#a0d4ee",
    "#9d8379",
    "#8e92b5",
    "#484d4d",
    "#ed454b",
    "#8a8986",
    "#a03b5c",
    "#86a7a1",
    "#af9e2e",
    "#6c1f28",
    "#476f9c",
    "#3897c5",
    "black" #FIXME
  ))
```

