---
title: "Bump chart replica"
---

# Import libraries
```{r}
library(tidyverse)
library(ggplot2)
library(ggtext)
library(httpgd)
```

```{#r}
hgd()
```
PARALLEL 
ver la evolución por generación, ya no por variable

# Import data
```{r}
df <- read_csv("https://github.com/carolinacornejocastellano/bump-chart/raw/main/data.csv")
# View(df)
```

# Pivot longer, add ranks and order chronologically
```{r}
df <- df %>%
  pivot_longer(-generation, names_to = "variables", values_to = "dollars") %>%
  group_by(generation) %>%
  arrange(generation, desc(dollars)) %>%
  mutate(ranking = row_number())

df$generation[df$generation == "silent"] <- "Silent"
df$generation[df$generation == "boomers"] <- "Boomers"
df$generation[df$generation == "gen_X"] <- "Generation X"
df$generation[df$generation == "millennials"] <- "Millennials"
df$generation[df$generation == "gen_Z"] <- "Generation Z"

df$variables[df$variables == "alcohol"] <- "Alcoholic beverages"
df$variables[df$variables == "apparel"] <- "Apparel and services"
df$variables[df$variables == "cash_contributions"] <- "Cash contributions"
df$variables[df$variables == "education"] <- "Education"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "food"] <- "Food"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "healthcare"] <- "Healthcare"
df$variables[df$variables == "housing"] <- "Housing"
df$variables[df$variables == "insurance"] <- "Personal insurance and pensions"
df$variables[df$variables == "miscellaneous"] <- "Miscellaneous expenditures"
df$variables[df$variables == "personal_care"] <- "Personal care products and services"
df$variables[df$variables == "reading"] <- "Reading"
df$variables[df$variables == "smoking"] <- "Tobacco products and smoking \n supplies"
df$variables[df$variables == "transportation"] <- "Transportation"
```

```{r}
x_names_ordered <- c("Silent", "Boomers", "Generation X", "Millennials", "Generation Z")
```

```{r}
x_names_full = c(
  "**Silent**<br>1945 or earlier<br>**$44,683**",
  "**Boomers**<br>1946 to 1964<br>**$62,203**",
  "**Generation X**<br>1965 to 1980<br>**$83,357**",
  "**Millennials**<br>1981 to 1996<br>**$69,061**",
  "**Generation Z**<br>1997 or later<br>**$41,636**"
)
```

```{r}
x_lab <- c("**Generation**<br>Birth Year Range<br>**Average Annual Expenditure**")
```

# Build custom theme

```{r}
theme_bump <- function() {
  # Colors
  color_background <- "#e5d9cf"
  color_text <- "black"

  # Begin construction of chart
  theme_bw(base_size = 15) +

    # Format background colors
    theme(panel.background = element_rect(fill = color_background, color = color_background)) +
    theme(plot.background = element_rect(fill = color_background, color = color_background)) +
    theme(panel.border = element_rect(color = color_background)) +
    theme(strip.background = element_rect(fill = color_background, color = color_background)) +

    # Format the grid
    theme(axis.ticks = element_blank()) +
    theme(panel.grid = element_line(colour = color_background)) +

    # Format the legend
    theme(legend.position = "none") +

    # Format de caption
    theme(plot.caption = element_text(hjust = 0.5, size = 9.5)) +

    # Format title and axis labels
    theme(plot.title = element_text(color = color_text, size = 20, face = "bold", hjust = 0.5)) +
    theme(plot.subtitle = element_text(color = color_text, size = 15, hjust = 0.5)) +
    theme(axis.title.x = element_blank()) +
    theme(axis.title.y = element_blank()) +
    theme(axis.text = element_markdown()) +
    theme(axis.text.x = element_markdown()) +
    theme(axis.text.x.top = element_markdown()) +
    theme(axis.text.y = element_blank()) +
    # theme(strip.text = element_text(face = "bold")) +
    theme(plot.tag = element_markdown()) +
    theme(plot.tag.position = c(0.15, 0.91)) +

    # Plot margins
    theme(plot.margin = unit(c(1, 0.2, 2, 0), "cm")) # top, right, bottom, left
}
```

# Bump chart 

```{r}
a <- ggplot(
  data = df,
  aes(x = generation, y = ranking, group = variables)) +
   theme_bump() +
     geom_line(aes(color = variables, alpha = 1, linewidth = rev(ranking))) +
     geom_point(size = 21, color = "white") +
     geom_point(aes(color = variables), size = 20) +
     scale_y_reverse(breaks = 1:nrow(df)) +
     scale_x_discrete(limits = x_names_ordered,
                  labels = x_names_full,
                  position = "top",
                  expand = expansion(mult = c(0.35, 0.1))) +
  labs(
    title = "HOW AMERICANS SPEND THEIR MONEY",
    subtitle = "By Age Group | 2021",
    caption = "Original author: Preethi Lodha",
    tag = x_lab
  ) +
    geom_text(data = df %>% filter(generation == "Silent"), aes(label = variables, x = 0.72), hjust = "outward", fontface = "bold", color = "black", size = 5) +
      geom_text(data = df, aes(label = dollars), hjust = "center", color = "white", size = 4.8) + # FIXME
      scale_color_manual(values = c(
        "#9c6255",
        "#a0d4ee",
        "#9d8379",
        "#8e92b5",
        "#484d4d",
        "#ed454b",
        "#8a8986",
        "#a03b5c",
        "#86a7a1",
        "#af9e2e",
        "#6c1f28",
        "#476f9c",
        "#3897c5",
        "black" # FIXME
      )) 
a
```

```{#r}
ggsave("bump-replica.png", path = "C:/Users/Carolina/0_ccast/master/04_dataviz/bump-chart/bump-chart", width = 10, height = 10, dpi = 300)
```
