---
title: "Bump chart replica"
---

# Import libraries
```{r}
library(tidyverse)
library(ggplot2)
library(ggtext)
library(grid)
library(ggrepel)
```

PARALLEL 
ver la evolución por generación, ya no por variable

# Import data
```{r}
df <- read_csv("https://github.com/carolinacornejocastellano/bump-chart/raw/main/data.csv")
#View(df)
```

# Pivot longer, add ranks and order chronologically
```{r}
df <- df %>%
  pivot_longer(-generation, names_to = "variables", values_to = "dollars") %>%
  #group_by(generation) %>%
  arrange(desc(dollars))

df$generation[df$generation == "silent"] <- "Silent"
df$generation[df$generation == "boomers"] <- "Boomers"
df$generation[df$generation == "gen_X"] <- "Generation X"
df$generation[df$generation == "millennials"] <- "Millennials"
df$generation[df$generation == "gen_Z"] <- "Generation Z"

df$variables[df$variables == "alcohol"] <- "Alcoholic beverages"
df$variables[df$variables == "apparel"] <- "Apparel and services"
df$variables[df$variables == "cash_contributions"] <- "Cash contributions"
df$variables[df$variables == "education"] <- "Education"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "food"] <- "Food"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "healthcare"] <- "Healthcare"
df$variables[df$variables == "housing"] <- "Housing"
df$variables[df$variables == "insurance"] <- "Personal insurance \n and pensions"
df$variables[df$variables == "miscellaneous"] <- "Miscellaneous expenditures"
df$variables[df$variables == "personal_care"] <- "Personal care products and services"
df$variables[df$variables == "reading"] <- "Reading"
df$variables[df$variables == "smoking"] <- "Tobacco products and smoking \n supplies"
df$variables[df$variables == "transportation"] <- "Transportation"
```


```{r}
x_names_ordered <- c("Silent", "Boomers", "Generation X", "Millennials", "Generation Z")
```

```{r}
x_names_full = c(
  "<span style='font-size: 9.55pt'>**Silent**</span><br>1945 or earlier<br>**$44,683**",

  "<span style='font-size: 9.55pt'>**Boomers**</span><br>1946 to 1964<br>**$62,203**",

  "<span style='font-size: 9.55pt'>**Generation X**</span><br>1965 to 1980<br>**$83,357**",

  "<span style='font-size: 9.55pt'>**Millennials**</span><br>1981 to 1996<br>**$69,061**",

  "<span style='font-size: 9.55pt'>**Generation Z**</span><br>1997 or later<br>**$41,636**"
)
```

```{r}
x_lab <- c("<span style='font-size: 10pt'>**Generation**</span><br>Birth Year Range<br>**Average Annual Expenditure**")
```

# Theme
```{r}
  # Colors
  color_background <- "#e5d9cf"
  color_text <- "#333333"

  theme_lines <- function() {

# Begin construction of chart
  theme_bw(base_size = 15) +

    # Format background colors
    theme(panel.background = element_rect(fill = color_background, color = color_background)) +
    theme(plot.background = element_rect(fill = color_background, color = color_background)) +
    theme(panel.border = element_blank()) +
    theme(strip.background = element_rect(fill = color_background, color = color_background)) +

    # Format the grid
    theme(axis.ticks = element_blank()) +
    theme(panel.grid = element_blank()) +

    # Format the legend
    theme(legend.position = "bottom") +
    theme(legend.background = element_blank()) +
    theme(legend.key = element_rect(fill = color_background)) +
    theme(legend.text	= element_markdown(color = color_text, size = 6.5, face = "bold")) +
    theme(legend.title = element_blank()) +
    theme(legend.direction = "horizontal") +
    theme(legend.spacing.x = unit(.3, 'cm')) +
      
    # Format de caption
    theme(plot.caption = element_text(hjust = 0.6, vjust= 0.1, size = 5.45)) +

    # Format title and axis labels
    theme(plot.title = element_text(color = color_text, size = 17.5, face = "bold", hjust = 0.5, margin=margin(0,0,10,0))) +
    theme(plot.subtitle = element_text(color = color_text, size = 11, hjust = 0.5, face = "bold", margin=margin(0,0,22,0))) +
    theme(axis.title.x = element_blank()) +
    theme(axis.title.y = element_blank()) +
    theme(axis.text = element_markdown()) +
    theme(axis.text.x = element_markdown()) +
    theme(axis.text.x.top = element_markdown(color = "#3b3b3a", family = "Arial Narrow", size=7.5)) +
    theme(axis.text.y = element_markdown()) +
    # theme(strip.text = element_text(face = "bold")) +
    theme(plot.tag = element_markdown(family = "Arial Narrow", lineheight = 0.1, size = 8)) +
    theme(plot.tag.position = c(0.10, 0.85)) +

    # Plot margins
    theme(plot.margin = unit(c(0.5, 0.4, 0.5, 0.65), "cm")) # top, right, bottom, left

}
```


# Plot
```{r}
set.seed(78)
df <- subset(df, variables %in% c(head(unique(df$variables))))

df %>% 
ggplot() +
  aes(x = generation, 
      y =dollars, 
      group = variables, 
      color= variables) +
geom_line(alpha = 0.6, size = 1.4) +
geom_point(size = 4, shape = 20, alpha = 0.6) +
geom_point(size = 3, shape = 1, color="white", alpha = 0.7, stroke = 0.7) +
  scale_x_discrete(
     limits = x_names_ordered,
     labels = x_names_full,
     position = "top",
     expand = expansion(mult = c(0.09, 0.1))
                  ) +
  scale_y_discrete(
    expand = expansion(mult = c(0.001, 0.001))
                  ) +
labs(
  title = "HOW AMERICANS SPEND THEIR MONEY",
  subtitle = "Top 6 categories by age group | 2021",
  caption = "Author: Preethi Lodha"
) +

# DOLLARS SPENT LABS  
   geom_text_repel(
    aes(label = paste0("$", (format(df$dollars, big.mark=",", trim=TRUE))),
      segment.square  = TRUE,
      segment.inflect = TRUE
    ),
    max.overlaps  = 2,
    size          = 2.5,
    fontface      = "bold",
    direction     = "y"
    ) +
guides(colour = guide_legend(nrow = 1)) +
scale_color_manual(values = c(
  "#ab3a6b",
  "#494c4d",
  "#3896c4",
  "#2f634a", 
  "#af9e2e",
  "#ed444a")) +
 coord_cartesian(clip = "off") +
      annotation_custom(
        linesGrob(
          x = c(0, 0.99), 
          y = c(1.13, 1.13), 
          gp = gpar(col = "#f0eae8", lwd = 2.8, lineend = "square"))) +
      annotation_custom(
        linesGrob(
          x = c(0, 0.99), 
          y = c(-0.05, -0.05), 
          gp = gpar(col = "#f0eae8", lwd = 2.8, lineend = "square"))) +
theme_lines()
```


```{#r}
    direction     = "x",
    vjust = 0.2,
    hjust = 2,
    segment.size  = 0.7,
    size          = 2.5,
    fontface      = "bold",
    box.padding = unit(0.2,"lines"),
```

```{r}
ggsave("enhancements.png", plot = last_plot(), path = "C:/Users/Carolina/0_ccast/master/04_dataviz/bump-chart/bump-chart", width = 8.29, height = 6.88, units = "in", dpi = 120)
```

   # 
