---
title: "Bump chart replica"
---

# Import libraries
```{r}
library(tidyverse)
library(ggplot2)
library(ggtext)
library(grid)
```

# Import data
```{r}
df <- read_csv("https://github.com/carolinacornejocastellano/bump-chart/raw/main/data.csv")
#View(df)
```

# Pivot longer, add ranks and order chronologically
```{r}
df <- df %>%
  pivot_longer(-generation, names_to = "variables", values_to = "dollars") %>%
  group_by(generation) %>%
  arrange(generation, desc(dollars)) %>%
  mutate(ranking = row_number())

df$generation[df$generation == "silent"] <- "Silent"
df$generation[df$generation == "boomers"] <- "Boomers"
df$generation[df$generation == "gen_X"] <- "Generation X"
df$generation[df$generation == "millennials"] <- "Millennials"
df$generation[df$generation == "gen_Z"] <- "Generation Z"

df$variables[df$variables == "alcohol"] <- "Alcoholic beverages"
df$variables[df$variables == "apparel"] <- "Apparel and services"
df$variables[df$variables == "cash_contributions"] <- "Cash contributions"
df$variables[df$variables == "education"] <- "Education"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "food"] <- "Food"
df$variables[df$variables == "entertainment"] <- "Entertainment"
df$variables[df$variables == "healthcare"] <- "Healthcare"
df$variables[df$variables == "housing"] <- "Housing"
df$variables[df$variables == "insurance"] <- "Personal insurance and pensions"
df$variables[df$variables == "miscellaneous"] <- "Miscellaneous expenditures"
df$variables[df$variables == "personal_care"] <- "Personal care products and services"
df$variables[df$variables == "reading"] <- "Reading"
df$variables[df$variables == "smoking"] <- "Tobacco products and smoking \n supplies"
df$variables[df$variables == "transportation"] <- "Transportation"
```

```{r}
# Add a comma in the appropriate place in each value of four or more digits in the dollar column
df$dollars <- format(df$dollars, big.mark=",", trim=TRUE)

# Paste the dollar sign at the beginning of each value in the "dollar" column
df$dollars <- paste0("$", df$dollars)

```


```{r}
x_names_ordered <- c("Silent", "Boomers", "Generation X", "Millennials", "Generation Z")
```

```{r}
x_names_full = c(
  "<span style='font-size: 9.55pt'>**Silent**</span><br>1945 or earlier<br>**$44,683**",

  "<span style='font-size: 9.55pt'>**Boomers**</span><br>1946 to 1964<br>**$62,203**",

  "<span style='font-size: 9.55pt'>**Generation X**</span><br>1965 to 1980<br>**$83,357**",

  "<span style='font-size: 9.55pt'>**Millennials**</span><br>1981 to 1996<br>**$69,061**",

  "<span style='font-size: 9.55pt'>**Generation Z**</span><br>1997 or later<br>**$41,636**"
)
```

```{r}
x_lab <- c("<span style='font-size: 10pt'>**Generation**</span><br>Birth Year Range<br>**Average Annual Expenditure**")
```


# Build custom theme

```{r}
theme_bump <- function() {
  # Colors
  color_background <- "#e5d9cf"
  color_text <- "#333333"

  # Begin construction of chart
  theme_bw(base_size = 15) +

    # Format background colors
    theme(panel.background = element_rect(fill = color_background, color = color_background)) +
    theme(plot.background = element_rect(fill = color_background, color = color_background)) +
    theme(panel.border = element_rect(color = color_background)) +
    theme(strip.background = element_rect(fill = color_background, color = color_background)) +

    # Format the grid
    theme(axis.ticks = element_blank()) +
    theme(panel.grid = element_line(colour = color_background)) +

    # Format the legend
    theme(legend.position = "none") +

    # Format de caption
    theme(plot.caption = element_text(hjust = 0.6, vjust= 0.1, size = 5.45)) +

    # Format title and axis labels
    theme(plot.title = element_text(color = color_text, size = 17.5, face = "bold", hjust = 0.5, margin=margin(0,0,10,0))) +
    theme(plot.subtitle = element_text(color = color_text, size = 11, hjust = 0.5, face = "bold", margin=margin(0,0,22,0))) +
    theme(axis.title.x = element_blank()) +
    theme(axis.title.y = element_blank()) +
    theme(axis.text = element_markdown()) +
    theme(axis.text.x = element_markdown()) +
    theme(axis.text.x.top = element_markdown(color = "#3b3b3a", family = "Arial Narrow", size=7.5)) +
    theme(axis.text.y = element_blank()) +
    # theme(strip.text = element_text(face = "bold")) +
    theme(plot.tag = element_markdown(family = "Arial Narrow", lineheight = 0.1, size = 8)) +
    theme(plot.tag.position = c(0.10, 0.85)) +

    # Plot margins
    theme(plot.margin = unit(c(0.5, 0.4, 0.5, 0.65), "cm")) # top, right, bottom, left
}
```

# Bump chart 

```{r fig.width = 8.29, fig.height = 6.88}
a <- ggplot(
  data = df,
  aes(x = generation, y = ranking, group = variables)) +
   theme_bump() +
     geom_line(aes(color = variables, alpha = 1, linewidth = rev(ranking))) +
     geom_point(size = 11.85, color = "white") +
     geom_point(aes(color = variables), size = 11.3) +
     scale_y_reverse(breaks = 1:nrow(df)) +
     scale_x_discrete(
       limits = x_names_ordered,
       labels = x_names_full,
       position = "top",
       expand = expansion(mult = c(0.356, 0.1))
                    ) +
  labs(
    title = "HOW AMERICANS SPEND THEIR MONEY",
    subtitle = "By Age Group | 2021",
    caption = "Author: Preethi Lodha",
    tag = x_lab
  ) +
    coord_cartesian(clip = "off") +
      annotation_custom(linesGrob(x = c(0, 0.99), y = c(1.11, 1.11), gp = gpar(col = "#f0eae8", lwd = 2.8, lineend = "square"))) +
      annotation_custom(linesGrob(x = c(0, 0.99), y = c(-0.05, -0.05), gp = gpar(col = "#f0eae8", lwd = 2.8, lineend = "square"))) +
        geom_text(data = df %>% filter(generation == "Silent"), aes(label = variables, x = 0.72236), hjust = "outward", fontface = "bold", color = "#272727", size = 2.4) +
      geom_text(data = df, aes(label = dollars), hjust = "center", color = "white", size = 2.25, fontface = "bold") +
      geom_text(data = df, aes(label = dollars), hjust = "center", color = "white", size = 2.253, fontface = "bold") +
      geom_text(data = df, aes(label = dollars), hjust = "center", color = "white", size = 2.257, fontface = "bold") +
      scale_color_manual(values = c(
        "#9c6255",
        "#a0d4ee",
        "#9d8379",
        "#8f93b5",
        "#494c4d",
        "#2f634a",
        "#ed444a",
        "#8a8887",
        "#a13b5d",
        "#87a7a0",
        "#af9e2e",
        "#6d1f29",
        "#466f9d",
        "#3896c4"
      )) 
a
```

```{#r}
ggsave("bump-replica.png", plot = last_plot(), path = "C:/Users/Carolina/0_ccast/master/04_dataviz/bump-chart/bump-chart", width = 8.29, height = 6.88, units = "in", dpi = 120)
```